language: c

before_script:
  - sudo apt update -qq
  - sudo apt install -y -qq build-essential autoconf automake pkg-config libtool m4 autoconf-archive gtk-doc-tools libxml2-utils gobject-introspection libgirepository1.0-dev libglib2.0-dev libjson-glib-dev cmake

script:
  - aclocal
  - autoconf
  - automake --add-missing
  - ./configure
  - make